languageCode: "en-us"
baseUrl: "https://blog.theinept.dev/"
title: "the inept blog"
theme: "anubis"
paginate: 10
disqusShortname: ""
googleAnalytics: "G-12345"
enableRobotsTXT: true

menu:
  main:
  # - identifier: home
  #   name: home
  #   title: home
  #   url: /
  #   weight: 1
  - identifier: posts
    name: posts
    title: posts
    url: /posts/
    weight: 2
  - identifier: about
    name: about
    title: about
    url: /about/
    weight: 3
  - identifier: tags
    name: tags
    title: tags
    url: /tags/
    weight: 4


params:
  author: "Gunner Clark"
  email: contact@gunnerclark.dev # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: ""
  # Uncomment if you need this
  images:
    - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark
  readMore: false # show read more button
  readNextPosts: 5  # show 5 related posts, 0 by default
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  # isso support
  isso:
    enabled: false # mandatory
    data: "https://comments.example.com/" # mandatory
    jsLocation: "https://comments.example.com/js/embed.min.js" # mandatory
    css: true # optional
    lang: "de" # optional
    replyToSelf: true # mandatory
    requireAuthor: true # mandatory
    requireEmail: true # mandatory
    id: "thread-id" # optional
    avatar: true # optional
    avatar-bg: "#f0f0f0" # optional
    feed: false # optional
  graphcommentId: ""
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:
  - id: github
    name: theineptdev
    url: "https://github.com/theineptdev/"
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown